# Generated by Django 2.2 on 2019-09-29 15:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacion',
            name='farmacologia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicacion',
            name='fisiopatologia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
