# Generated by Django 2.2 on 2019-10-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicaciones', '0002_auto_20190929_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacion',
            name='farmacologia',
        ),
        migrations.AlterField(
            model_name='indicacion',
            name='imagen',
            field=models.ImageField(default=1, upload_to='indicacion'),
            preserve_default=False,
        ),
    ]
