# Generated by Django 2.2 on 2020-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicaciones', '0003_auto_20191001_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre categoria')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='indicacion',
            name='modo_oculto',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=30),
        ),
        migrations.AddField(
            model_name='indicacion',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='indicacion'),
        ),
        migrations.AddField(
            model_name='indicacion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='get_posts', to='indicaciones.Departamento', verbose_name='Categoría'),
        ),
    ]
