# Generated by Django 2.2 on 2020-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='get_posts', to='blog.SubCategory', verbose_name='Subcategoría'),
        ),
    ]
