# Generated by Django 2.2 on 2019-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantas', '0001_initial'),
        ('indicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('composicion', models.TextField(blank=True, null=True)),
                ('pvp', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('posologia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('linkamazon', models.URLField(blank=True, null=True)),
                ('linkpromofarma', models.URLField(blank=True, null=True)),
                ('indicaciones', models.ManyToManyField(blank=True, null=True, related_name='indicacionesproducto', to='indicaciones.Indicacion')),
                ('plantas', models.ManyToManyField(related_name='plantasproducto', to='plantas.Planta')),
            ],
        ),
    ]
