# Generated by Django 2.2 on 2020-05-06 16:35

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0007_auto_20200506_1635'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-media2', 'pvp']},
        ),
        migrations.AddField(
            model_name='producto',
            name='estandarizacion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='evidencias',
            field=models.ManyToManyField(blank=True, related_name='productos', to='plantas.Evidencia'),
        ),
        migrations.AddField(
            model_name='producto',
            name='laboratorio',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='media2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='puntoextra',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='pvp_amazon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='pvp_promofarma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='valoracion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='composicion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default=1, upload_to='productos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='indicaciones',
            field=models.ManyToManyField(blank=True, related_name='indicacionesproducto', to='indicaciones.Indicacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='plantas',
            field=models.ManyToManyField(blank=True, related_name='plantasproducto', to='plantas.Planta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pvp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Dosisproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosisproducto', to='plantas.Planta')),
            ],
            options={
                'ordering': ['planta'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='dosis',
            field=models.ManyToManyField(blank=True, to='productos.Dosisproducto'),
        ),
    ]
