# Generated by Django 2.2 on 2019-09-23 10:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('droga', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(max_length=100, unique=True)),
                ('posologia', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('activos', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mecanismo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contraindicaciones', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('interacciones', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('embarazo', models.CharField(choices=[('SI', 'Droga segura'), ('NO', 'Droga no recomendada'), ('BPM', 'Bajo prescripción médica')], default='NO', max_length=5)),
                ('lactancia', models.CharField(choices=[('SI', 'Droga segura'), ('NO', 'Droga no recomendada'), ('BPM', 'Bajo prescripción médica')], default='NO', max_length=5)),
                ('edad', models.CharField(choices=[('0', 'Cero meses'), ('2', 'Dos años'), ('3', 'Tres años'), ('6', 'Seis años'), ('10', 'Diez años'), ('12', 'Doce años'), ('18', '18 años')], default='12', max_length=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plantas')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['especie'],
                'managed': False,
            },
        ),
    ]
