#Generated by Django 2.2 on 2019-09-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ['especie']},
        ),
    ]
