# Generated by Django 2.2 on 2019-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('indicaciones', '0001_initial'),
        ('plantas', '0002_auto_20190923_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='indicaciones',
            field=models.ManyToManyField(related_name='indicacionplanta', to='indicaciones.Indicacion'),
        ),
        migrations.AddField(
            model_name='planta',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='productoplanta', to='productos.Producto'),
        ),
    ]
