# Generated by Django 2.2 on 2019-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_auto_20190923_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='usos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
