# Generated by Django 2.2 on 2019-09-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_planta_usos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ['nombre']},
        ),
    ]
