# Generated by Django 2.2 on 2019-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_auto_20190927_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='edad',
            field=models.CharField(choices=[('0', 'Cero meses'), ('2', 'Dos años'), ('3', 'Tres años'), ('4', 'Cuatro años'), ('6', 'Seis años'), ('10', 'Diez años'), ('12', 'Doce años'), ('16', '16 años'), ('18', '18 años')], default='12', max_length=5),
        ),
    ]
