# Generated by Django 2.2 on 2020-05-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicaciones', '0004_auto_20200506_1635'),
        ('plantas', '0006_auto_20191001_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='productos',
        ),
        migrations.AddField(
            model_name='planta',
            name='dosis_efectiva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='embarazo',
            field=models.CharField(choices=[('SI', 'Su empleo es seguro'), ('NO', 'Su empleo no está recomendado'), ('BPM', 'Bajo prescripción médica')], default='NO', max_length=5),
        ),
        migrations.AlterField(
            model_name='planta',
            name='indicaciones',
            field=models.ManyToManyField(blank=True, related_name='indicacionplanta', to='indicaciones.Indicacion'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='lactancia',
            field=models.CharField(choices=[('SI', 'Su empleo es seguro'), ('NO', 'Su empleo no está recomendado'), ('BPM', 'Bajo prescripción médica')], default='NO', max_length=5),
        ),
        migrations.AlterField(
            model_name='planta',
            name='usos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 'uno'), (2, 'dos'), (3, 'tres'), (4, 'cuatro'), (5, 'cinco')])),
                ('indicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='indicaciones.Indicacion')),
            ],
            options={
                'ordering': ['indicacion'],
            },
        ),
        migrations.AddField(
            model_name='planta',
            name='evidencias',
            field=models.ManyToManyField(blank=True, related_name='plantas', to='plantas.Evidencia'),
        ),
    ]
